In [53]:
import torch

In [54]:
_ = torch.arange(100)
len(_)


100

In [55]:
_.shape

torch.Size([100])

In [128]:
a = torch.arange(20).reshape(4,5)
a

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [129]:
a.T

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

In [130]:
b = torch.zeros_like(a)
b

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [131]:
b*a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [134]:
print(a)
a.sum(axis=0)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])


tensor([30, 34, 38, 42, 46])

In [61]:
a = a.to(dtype=torch.float16)
print(a.shape)
mean_a = a.mean(axis=1,keepdims=True)
print(mean_a)

torch.Size([4, 5])
tensor([[ 2.],
        [ 7.],
        [12.],
        [17.]], dtype=torch.float16)


In [63]:
print(a)
a/mean_a

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]], dtype=torch.float16)


tensor([[0.0000, 0.5000, 1.0000, 1.5000, 2.0000],
        [0.7144, 0.8569, 1.0000, 1.1426, 1.2861],
        [0.8335, 0.9165, 1.0000, 1.0830, 1.1670],
        [0.8823, 0.9414, 1.0000, 1.0586, 1.1172]], dtype=torch.float16)

# 矩阵的点积

In [83]:
a = torch.tensor([1,2,3],dtype=torch.float)

In [84]:
b = torch.ones(a.shape)+1
b

tensor([2., 2., 2.])

In [85]:
torch.sum(a*b)

tensor(12.)

In [86]:
a,b

(tensor([1., 2., 3.]), tensor([2., 2., 2.]))

In [88]:
torch.dot(a,b)

tensor(12.)

# 矩阵的向量积
矩阵乘以一维的向量

In [105]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [110]:
a1 = torch.ones(4,dtype=torch.int64)
a1

tensor([1, 1, 1, 1])

In [111]:
torch.mv(A,a1)

tensor([ 6, 22, 38, 54, 70])

# 矩阵乘法

In [113]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
B = torch.tensor([[7, 8], [9, 10], [11, 12]], dtype=torch.float32)
A,B

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]))

下面这三种用法是等效的，但是也有一点区别
`@`符号是矩阵乘的简化写法

`torch.mm` 和 `torch.matmul` 都是 PyTorch 中用于矩阵乘法的函数，但它们的行为在处理不同维度的输入时有所不同。

### torch.mm

- `torch.mm` 只接受两个二维张量（即矩阵）作为输入，并返回两个矩阵的乘积作为输出。
- 如果尝试用 `torch.mm` 对非二维张量进行乘法运算，将会抛出错误。
- 它仅仅执行标准的矩阵乘法，没有广播（broadcasting）功能。

### torch.matmul

- `torch.matmul` 是一个更通用的矩阵乘法函数，它可以处理两个张量的乘法，这两个张量可以是任意维度。
- 当输入是二维张量时，`torch.matmul` 的行为和 `torch.mm` 相同。
- 当输入包含高于二维的张量时，`torch.matmul` 会执行批量矩阵乘法操作。在这种情况下，它会将输入张量的额外维度视为批量大小，并对每个批量执行矩阵乘法。
- `torch.matmul` 支持广播功能。如果两个张量的维度不匹配，但是它们可以根据广播规则扩展到相同的维度，则 `torch.matmul` 会自动扩展它们以执行乘法。

In [116]:
torch.mm(A,B),torch.matmul(A,B),A@B

(tensor([[ 58.,  64.],
         [139., 154.]]),
 tensor([[ 58.,  64.],
         [139., 154.]]),
 tensor([[ 58.,  64.],
         [139., 154.]]))

In [118]:
# 创建一个3维张量，大小为 2x2x3
C = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], dtype=torch.float32)

# 创建一个2x3的矩阵
D = torch.tensor([[7, 8], [9, 10], [11, 12]], dtype=torch.float32)
C,D

(tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.]],
 
         [[ 7.,  8.,  9.],
          [10., 11., 12.]]]),
 tensor([[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]))

In [120]:
C@D,torch.matmul(C,D)

(tensor([[[ 58.,  64.],
          [139., 154.]],
 
         [[220., 244.],
          [301., 334.]]]),
 tensor([[[ 58.,  64.],
          [139., 154.]],
 
         [[220., 244.],
          [301., 334.]]]))

# 范数

In [136]:
u=torch.tensor([3.0,4.2,6.7])
torch.norm(u)

tensor(8.4575)