In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [2]:
def load_array(data_arrays, batch_size, is_train=True):  #@save
    """构造一个PyTorch数据迭代器"""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [3]:
next(iter(data_iter))

[tensor([[-0.7608, -1.2345],
         [-0.4173,  0.7219],
         [-0.1612, -0.6910],
         [-1.2045,  0.0146],
         [ 1.4052,  2.0262],
         [ 1.0510, -0.6267],
         [ 2.7560,  0.4470],
         [-0.1873,  0.0870],
         [-0.2271,  0.6954],
         [ 1.8780, -0.8010]]),
 tensor([[ 6.8957],
         [ 0.9267],
         [ 6.2388],
         [ 1.7572],
         [ 0.1150],
         [ 8.4353],
         [ 8.1940],
         [ 3.5269],
         [ 1.3808],
         [10.6695]])]

In [4]:
# nn是神经网络的缩写
from torch import nn

net = nn.Sequential(nn.Linear(2, 1))

In [5]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [10]:
net[0].bias.data

tensor([0.])

In [11]:
loss = nn.MSELoss()

In [13]:
next(net.parameters())

Parameter containing:
tensor([[-0.0026, -0.0049]], requires_grad=True)

In [14]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

训练过程
1. 通过调用net(X)生成预测并计算损失l（前向传播）。
2. 通过进行反向传播来计算梯度。
3. 通过调用优化器来更新模型参数。

In [15]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X) ,y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000285
epoch 2, loss 0.000100
epoch 3, loss 0.000100


In [16]:
w = net[0].weight.data
print('w的估计误差：', true_w - w.reshape(true_w.shape))
b = net[0].bias.data
print('b的估计误差：', true_b - b)

w的估计误差： tensor([ 6.8128e-04, -6.1512e-05])
b的估计误差： tensor([-0.0007])
